// Include the standard input/output stream library so we can print messages to the console
#include <iostream>
// Include the order book header file to interact with the matching engine
#include "lob/order_book.hpp"

// The main entry point where execution of our matching engine application starts
int main() {
    // Print an introductory message to show the application is launching
    std::cout << "Starting the Low-Latency Matching Engine..." << std::endl;

    // Create an instance of the OrderBook class to hold bids and asks
    lob::OrderBook book;

    // Construct a sample buy order with ID 1, price 100, quantity 10, and Side Buy
    lob::Order new_buy_order(1, 100, 10, lob::Side::Buy);

    // Print details about the order we are about to insert into the book
    std::cout << "Adding order: ID=" << new_buy_order.id 
              << ", Price=" << new_buy_order.price 
              << ", Qty=" << new_buy_order.qty 
              << ", Side=" << lob::side_to_string(new_buy_order.side) << std::endl;

    // Add the sample order to the order book and capture any executed trades (which should be none for now)
    auto trades = book.add_order(new_buy_order);

    // Print the number of trades generated by adding this order (expected to be 0)
    std::cout << "Trades generated: " << trades.size() << std::endl;

    // Try to cancel the order we just added using its ID (1)
    bool is_cancelled = book.cancel_order(1);

    // Print whether the cancellation was successful or not
    std::cout << "Order 1 cancellation status: " << (is_cancelled ? "SUCCESS" : "FAILED") << std::endl;

    // Check if the book is empty now after cancellation and print the result
    std::cout << "Is order book empty? " << (book.empty() ? "YES" : "NO") << std::endl;

    // Return 0 to indicate the application terminated successfully
    return 0;
}
